2021-06-08 18:04:57,887 dellemc_isilon_gatherfacts.py INFO : Got python SDK instance for provisioning on Isilon 
2021-06-08 18:07:07,215 connectionpool.py WARNING : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fab0f4e5ac8>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /session/1/session
2021-06-08 18:08:10,975 dellemc_isilon_gatherfacts.py INFO : Got python SDK instance for provisioning on Isilon 
2021-06-08 18:10:21,775 connectionpool.py WARNING : Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb8543b2ac8>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /session/1/session
2021-06-08 18:12:32,847 connectionpool.py WARNING : Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb8543b2be0>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /session/1/session
